 version: 0.2
 phases:
   install:
     commands:
       - echo "Installing frontend and backend via Docker builds..."
      - sudo yum install nginx -y
      - docker build -t frontend-image ./application-code/web-tier
      - docker build -t backend-image ./application-code/app-tier
  build:
    commands:
      - echo "Running Docker containers..."
      - docker run -d --name frontend-container -p 81:80 frontend-image
      - docker run -d --name backend-container -p 4000:4000 backend-image
      - echo "Docker containers started successfully."

env:
  variables:
    AWS_REGION: "ap-south-1"
    IMAGE1_NAME: "<account_id>.dkr.ecr.us-east-1.amazonaws.com/frontend-image"
    IMAGE2_NAME: "<account_id>.dkr.ecr.us-east-1.amazonaws.com/backend-image"
    

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $IMAGE1_NAME
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $IMAGE2_NAME

  build:
    commands:
      - echo Tagging and pushing image...
      - docker tag image1:latest $IMAGE1_NAME:latest
      - docker tag image2:latest $IMAGE2_NAME:latest
      - docker push $IMAGE1_NAME:latest
      - docker push $IMAGE2_NAME:latest
      


  files:
    - appspec.yml
    - scripts/*
    - application-code/web-tier/Dockerfile
    - application-code/app-tier/Dockerfile
